# /src/main/resources/private-key.properties
private.app.website=  <website>
app.organization_name=  <organization_name>
app.email=  <EMAIL>
app.phone= <phone>
app.webname= <webname>

DB_USERNAME= <username>
DB_PASSWORD= <PASSWORD>

mail.username=
mail.password=

aliyun.accessKeySecret=
aliyun.bucketName=
aliyun.accessKeyId=
aliyun.roleArn=
CDNPoint=

nacos.password=